[package]
name = "app"
version = "0.1.0"
authors = ["Vincent Hiribarren <vhiribarren@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raytracer = { path = "../raytracer" }